### ISSUE TITLE
require(phpMQTT.php): failed to open stream: No such file

### ISSUE THREAD

**Issue by BL-Lau** [vvaswani/bluemix-iotf-device-tracker#1]
Hi, 
I am an Android app developer and exploring IoT Starter. I am new to PHP, when I access cli-app.php on my hosted server, I encounter the above error. Do I need to load phpMQTT.php to my server ? 

Appreciate your helps , thanks !

Best regards,
BL

**Comment by BL-Lau** [comment]
Hi Mr Vikram, 
I found and loaded phpMQTT to my server, but I get into another problem:
"Warning: fsockopen(): unable to connect to 169.45.2.20:1883 (Connection timed out) in .../phpMQTT.php on line 78
ERROR: Could not connect to IoT cloud"

Thanks !

Best regards,
BL

**Comment by vvaswani** [comment]
Have you set an org ID and used the correct API key and token?

You can also use http://www.hivemq.com/demos/websocket-client/ to test connectivity to the IoTF servers.

**Comment by BL-Lau** [comment]
Thanks for your quick reply. 
Yes, I registered with Watson IoT Platform, have org id and generated API Key and Authentication Token. I entered these info into cli-app.php. 

I also tried telnet 169.45.2.20 using port 8883, 1883 and 443, all failed to connect.

By the way, how do I use HiveMQ from the link above ? What do I need to enter for Host, Port, Client-id, name, password, etc ? 

Appreciate your helps. Thanks !

**Comment by BL-Lau** [comment]
I tried to use HiveMQ as follows:
Host: org_id.messaging.internetofthings.ibmcloud.com   Port: 1883  client-id: API key

I get response as: 
Connect failed: AMQJS0006E Bad Connack return code:5 
Connection Refused: not authorised.

**Comment by BL-Lau** [comment]
I make another attempt to use HiveMQ
Host: org_id.messaging.internetofthings.ibmcloud.com Port: 1883 client-id: a:org_id:app_id
username: iotf_api_key   password: iotf_api_secret

I am CONNECTED !!!

**Comment by BL-Lau** [comment]
Sadly, cli-app.php or web-app.php still have the same problem...

**Comment by vvaswani** [comment]
If you are able to connect using HiveMQ (and presumably see a data stream from your device), this indicates that your IoTF setup is functioning. The problem is with the PHP scripts which cannot connect to IoTF. 

* Please check if there is a firewall that is preventing outbound connections.
* You can also try setting `$mqtt->debug = true;`. 
* If these fail, check the code of the phpMQTT class constructor and try to manually set a higher timeout value in the call to `fsockopen()` or add debug statements in phpMQTT to better identify where the problem is arising from.

**Comment by BL-Lau** [comment]
Thanks for your kind advice, I checked with my server host and they opened port 1883 for me. 

After that, we I ran cli-app.php script with $mqtt->debug = true, I got the message "Connected to Broker eof receive going to reconnect for good measure". The message kept repeating. When I turned debug to false, the error was "Fatal error: Maximum execution time of 60 seconds exceeded in ...myserver.../phpMQTT.php on line 167" (sometimes line 169).

On the other hand, I used HiveMQ, entered the topic "iot-2/type/+/id/device_id/evt/accel/fmt/json, I was able to see data streaming in. 

What should I do to fix the above error ?

**Comment by vvaswani** [comment]
It seems that phpMQTT is timing out while waiting for the data stream. This could be due to a slow network connection. Perhaps you could try these solutions:

 * Change the timeout value in the call to `fsockopen` in the phpMQTT code: https://github.com/bluerhinos/phpMQTT/blob/master/phpMQTT.php#L78. See http://php.net/fsockopen for information on the parameters.
 * Try setting a higher script timeout value for the cli-app script: http://php.net/manual/en/function.set-time-limit.php

Please check if this error also occurs with the `web-app.php` script or only with the `cli-app.php` script.

**Comment by BL-Lau** [comment]
I checked with my server host and was told that my shared server hosting does not allow data coming in from other server. I suppose that's the reason I am not able to stream data to phpMQTT, is it correct ?

**Comment by vvaswani** [comment]
I'm not sure if that's the reason as previously you stated you saw the message "Connected to Broker". To check if this is the issue, you can set up a local PHP environment or try another server where you have control over the firewall.
 
Alternatively, try adjusting the various timeouts as suggested in my last response in case it is a slow network and the script/socket is timing out.

**Comment by BL-Lau** [comment]
I changed the timeout value in the call to fsockopen in the phpMQTT code from 60 to 120, when I ran the 2 scripts:
a.) cli-app.php, I still get "Fatal error: .../phpMQTT.php on line 167"
b.) web-app.phon, I got "No GPS data available"

I added "set_time_limit(60);" at the first line of cli-app.php script, I still get the same fatal error

On the other hand, HiveMQ data stream was fast and almost instantaneous.

**Comment by BL-Lau** [comment]
Additional observations when I add a few echo in web-app.php:
a.) When I added "echo $topics" after the line "$topics['iot-2/type/+/id/' . $config['device_id']....."
I only saw "array"
b.) When I added "echo 'within while loop'" inside the "while ($mqtt->proc(true))" loop, I can see that it was being repeated 
c.) When I added "echo "'if true'" inside the "if (count($location) == 2) {" , it was not printed out.

**Comment by vvaswani** [comment]
If you are seeing GPS data using HiveMQ but not in the web-app.php file, then please try this using a different PHP server as perhaps your initial note (that the server is blocking inbound data from IoTF) is correct.

**Comment by BL-Lau** [comment]
Dear Mr Vikram, 
I am not sure when I can get another PHP server, but your codes are sound.
Thank you very much for all your helps, I appreciate your efforts. 
I shall close the topic if you agree.
Best regards,
BL

**Comment by vvaswani** [comment]
I'm sorry you couldn't get it working. To debug this further further and see if the issue is the firewall, I think you would need a PHP server where you can modify firewall rules or that allows open connections. Feel free to close the issue if you think appropriate.

**Comment by vvaswani** [comment]
You can also set up the app (web app only) on Bluemix, which should hopefully allow inbound data from IoTF (if that is indeed the problem). For an example of how to do this, see Step 7 of http://www.ibm.com/developerworks/library/mo-assist-stray-dogs-2-premium/index.html

**Comment by BL-Lau** [comment]
I managed to setup PHP on Bluemix CloudFoundry, and verified that it worked when it responded with "Hello World" on link: https://bl-mqtt.mybluemix.net/hello.php 

Then, I cf pushed cli-app.php and web-app.php. I ran https://bl-mqtt.mybluemix.net/cli-app.php and https://bl-mqtt.mybluemix.net/web-app.php. 

However, I got the same problem as in my hosted server, i.e.: 
a) cli-app.php : web page response: "Connected to Broker eof receive going to reconnect for good measure", it kept repeating, but I don't get streaming data from my device. I verified that data streaming was active and instantaneous on HoveMQ. Even if I turned off my device,  I continued to receive the same repeated message.
b) web-app.php : web page response: "No GPS data available."

Any comment ?

**Comment by vvaswani** [comment]
It seems most likely this is a problem with phpMQTT and its socket connections. I see a number of similar issues here: https://github.com/bluerhinos/phpMQTT/issues. I think you would need to tweak the phpMQTT code to resolve this.

I would be happy to debug this further but I no longer have the Android Starter APK to stream data, so unfortunately cannot set up the necessary test environment at the current time.

**Comment by vvaswani** [comment]
Two further thoughts: 

 * If your device is constantly streaming, you could give me access to the data stream via an API key (please don't post it in this public forum) and I can then try to debug it further. 
* Or, since you are able to successfully use Hive, you could try using the PHP scripts with the Hive broker instead of the IoTF broker. In this case, you would publish messages to a topic manually using the Hive online client, then attempt to receive those messages using the `cli-app.php` or `web-app.php` scripts (obviously modifying the host name, credentials and topic to work for Hive).

**Comment by BL-Lau** [comment]
If it doesn't consume too much of your time, I will be willing to turn on my device for say 24-48 hours continuously for your to debug. Please let me know when you would like to do that and how to send the API key to you. Thanks for your helps.

**Comment by vvaswani** [comment]
That seems fine. Please send me the following information:
- Device and org ID
- API credentials
- Time during which the stream will be live

You can send me this information privately via [this form](http://vikram-vaswani.in/) or via my [LinkedIn page](http://www.linkedin.com/in/vvaswani).

**Comment by BL-Lau** [comment]
Thanks for your kind helps. 

I tried http://vikram-vaswani.in/contact/, but there is error "The CAPTCHA value entered was incorrect. Please try again." 

I sent invitation from LinkedIn with the above details inside there, not sure whether the message has gone through. 

I have the device turned on until you notify me to stop.

**Comment by vvaswani** [comment]
I just tried the contact form and it works well. Did you tick the CAPTCHA button to confirm "you are not a robot"? I have also received the LinkedIn invitation but there were no credentials provided in the message.

**Comment by vvaswani** [comment]
I have received the credentials now. I will post my results here once I have completed debugging.

**Comment by BL-Lau** [comment]
I tried again, the contact form works. I did clicked the "I am not a robot" button in the earlier submission...

I look forward to your post after the debugging. Thanks!

**Comment by vvaswani** [comment]
I have updated the QoS to 1, earlier 0, and it seems to be working now. Please check and close this issue if all is working correctly, or post new debug information.

**Comment by vvaswani** [comment]
If closing the issue, please also revoke the API key sent privately to me earlier for security reasons.

**Comment by BL-Lau** [comment]
Yes, the problem is fixed ! I can see data streaming to my hosted server.
Thank you very much for all your helps.
I have also removed the API key that I sent your privately earlier. 
I hereby close this issue.
